services:
  - type: web
    name: icecream-ratings
    runtime: node
    repo: https://github.com/tbtz/icecream-ratings
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_VERSION
        value: 20
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start